name: xfunding
description: A new Flutter project.


publish_to: 'none'

version: 3.0.0+3

environment:
  sdk: ">=3.4.1 <4.2.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: 5.9.3
  google_fonts: 6.2.1
  font_awesome_flutter: 10.7.0
  country_code_picker: 3.0.0
  image_picker: 1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: 4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/splash/
    - assets/images/onboard/
    - assets/images/bg/
    - assets/images/country/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

